modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/daPoseidonGuy/strawgolem"
[[mods]] #mandatory
    modId="strawgolem"
    version="1.5"
    displayName="Straw Golem"
    credits="nivoridocs, for making this mod"
    authors="CommodoreThrawn & nivoridocs" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''
    Adds a straw golem to help with farming
    '''