modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
issueTrackerURL="https://github.com/daPoseidonGuy/strawgolem"
[[mods]] #mandatory
    modId="strawgolem"
    version="1.14.4-1.9"
    displayName="Straw Golem"
    credits="nivoridocs, for making the original mod\nFrenderman, for making the updated golem model, testing and design ideas"
    authors="CommodoreThrawn" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''
    Adds a straw golem to help with farming
    '''